name: Storybook
on:
  push:
    branches:
      - Sebastian-ubs/issue411
    paths: ['src/stories/**', 'lib/papi-components/src/**']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm ci
          npm run storybook:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: github-pages
          folder: storybook-static
          GITHUB_TOKEN: ${{ secrets.PAGES_PAT }}
          
