name: Test

on:
  push:
    branches: ['main']
  pull_request:
    # The branches below should be a subset of the branches above
    branches: ['main']
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  test:
    name: Build on ${{ matrix.os }}, .Net ${{ matrix.dotnet_version }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        dotnet_version: [8.0.x]

    steps:
      - name: Install MacPorts
        if: ${{ matrix.os == 'macos-latest' }}
        uses: melusina-org/setup-macports@v1

      - name: Install icu4c on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: sudo port -v install icu

      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet_version }}

      - name: Read package.json
        id: package_json
        uses: zoexx/github-action-json-file-properties@1.0.6
        with:
          file_path: 'package.json'

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: ${{ fromJson(steps.package_json.outputs.volta).node }}
          cache: npm

      - name: npm install
        run: npm install

      - name: Build
        run: npm run build

      - name: dotnet unit tests
        run: dotnet test c-sharp-tests/c-sharp-tests.csproj

      - name: npm unit tests
        run: npm test

      - name: check dotnet formatting
        run: |
          cd c-sharp
          dotnet tool restore
          dotnet csharpier --check .

      - name: check JS/TS formatting
        run: npm run format:check

      - name: check JS/TS linting
        run: npm run lint

      - name: check packaging
        env:
          # no hardlinks so dependencies are copied
          USE_HARD_LINKS: false
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run package

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
